# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 言午沖
email: xuchong@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
            Blog of Xu Chong, Studying, Living, Creating .
            Love U & Me
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xuchong.github.com" # the base hostname & protocol for your site
googleplus_url: "https://plus.google.com/102544969444435690765"
github_username:  xuchong

# Build settings
markdown: kramdown

#own settings
repository: "xuchong/xuchong.github.io"

theme: jekyll-theme-modernist